---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400 # 1 day

- jm1.pkg.meta_pkg:
    name: "jm1-dev-python"
    version: "1"
    depends:
    - cython3
    - ipython3
    - flake8
    - pipenv
    - pycodestyle # formerly called pep8
    - pypy
    - pypy-doc
    - pyqt5-dev
    - pyqt5-dev-tools
    - pyqt5-examples
    - python3-pip
    - python3-virtualenv
    - python3-pytest
    - swig
    suggests:
    - pipx
